### ISSUE TITLE
Remove optional chaining to support LTS Node version

### ISSUE THREAD

**Issue by hstandaert** [Jeday/react-docx#9]
Unfortunately, optional chaining is only available as of Node.js `v14.x`. The LTS version is now at `v12.18.3`, so it would be nice if that is supported as well.

I've been trying to use the package with node `v12.x` and the only hiccup I've come accross is the optional chaining in: https://github.com/Jeday/react-docx/blob/74e9b2e33940bbb951b1f7a17ae288d1cfca9dc4/src/reconciler/index.js#L66-L70

**Comment by Jeday** [comment]
Absolutely I will get on to it when I have some free time. I thought maybe use babel to build project for Node LTS. Or even just manually remove optional chaining if there is not much of it in the project.

**Comment by Jeday** [comment]
I uploaded updated version with transpiled cjs bundle to npm. Please report any problems with newest version and I will try to deal with them asap.

**Comment by hstandaert** [comment]
Thanks to fix this so quickly, @Jeday 👍
